# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.destroy_all
Snack.destroy_all

snack1 = Snack.create!(name: 'Airheads Xtremes Rainbow Berry Sour Candy Belts', description: 'Pack of 12, 3 oz. bags', price: 3999)
snack2 = Snack.create!(name: 'Big Sour Patch Kids Chewy Candy', description: 'Individually wrapped, 240 count box', price: 1358)
snack3 = Snack.create!(name: 'Jolly Rancher Assorted Fruit Flavored Hard Candy', description: '360 individually wrapped pieces, 5 lb. bag', price: 2349)
snack4 = Snack.create!(name: 'Life Savers Hard Candy 5 Flavors', description: '50 oz. party size bag', price: 899)
snack5 = Snack.create!(name: 'Mentos Chewy Mint Fruit Candy', description: 'Pack of 6, 15 piece rolls', price: 1816)
snack6 = Snack.create!(name: 'Nerds Rope Rainbow Candy', description: 'Pack of 24, 0.92 oz. packages', price: 1899)
snack7 = Snack.create!(name: 'Red Vines Original Red Licorice Candy Twists', description: '3.5 lb. container', price: 872)
snack8 = Snack.create!(name: "Reese's, Hershey's, and Kit Kat Assorted Milk Chocolate Miniatures Candy", description: 'Individually wrapped, 265 piece bag', price: 2595)
snack9 = Snack.create!(name: 'Ring Pop Assorted Flavor Lollipops Party Pack', description: '20 count bag', price: 698)
snack10 = Snack.create!(name: "M&M's Snickers 3 Musketeers Skittles Starburst Variety Mix", description: '30 full size packs', price: 3335)
snack11 = Snack.create!(name: 'Snickers Twix 3 Musketeers Milky Way Chocolate Variety Mix', description: '240 inividually wrapped pieces', price: 3124)
snack12 = Snack.create!(name: 'Tootsie Roll Chocolate Twist Midgees', description: '700 count, resealable bag', price: 1911)
snack13 = Snack.create!(name: "Cheetos Lay's Fritos Ruffles Funyuns Doritos Variety Pack", description: '40 count party mix', price: 1798)
snack14 = Snack.create!(name: 'Doritos Cool Ranch Tortilla Chips', description: '14.5 oz. party size bag', price: 450)
snack15 = Snack.create!(name: 'Kettle Brand Organic Sea Salt Potato Chips', description: '5 oz. bag', price: 329)
snack16 = Snack.create!(name: 'Pringles Potato Crisp Chips Variety Pack Snack Stacks', description: 'Pack of 36, 0.67 oz. cups', price: 1499)
snack17 = Snack.create!(name: 'Ruffles Original Potato Chips', description: '13 oz. party size bag', price: 469)
snack18 = Snack.create!(name: 'Ruffles Cheddar & Sour Cream Potato Chips', description: '12.5 oz. party size bag', price: 459)
snack19 = Snack.create!(name: 'Ruffles Sour Cream & Onion Potato Chips', description: '8 oz. bag', price: 399)
snack20 = Snack.create!(name: 'Sunchips Multigrain Chips Variety Pack', description: '40 count pack', price: 1398)
snack21 = Snack.create!(name: "Sunchips Smartfood Doritos Lay's Cheetos Variety Pack", description: '35 count pack', price: 1499)
snack22 = Snack.create!(name: 'Tostitos Hint of Lime Tortilla Chips', description: '11 oz. bag', price: 349)
snack23 = Snack.create!(name: 'Tostitos Scoops Tortilla Chips', description: '10 oz. bag', price: 399)
snack24 = Snack.create!(name: 'Biscoff Lotus Cookies', description: '20 packs, 2 cookies per pack', price: 1090)
snack25 = Snack.create!(name: 'Chips Ahoy Original & Chewy Chocolate Chip Cookies Bundle', description: '3 family size packages', price: 1266)
snack26 = Snack.create!(name: 'Famous Amos Chocolate Chip Cookies', description: 'Pack of 36, 2 oz. pouches', price: 1918)
snack27 = Snack.create!(name: "Grandma's Cookies Variety Pack", description: 'Pack of 30', price: 1498)
snack28 = Snack.create!(name: 'Oreo Chips Ahoy Nutter Butter Cookie Snacks Variety Pack', description: '56 snack packs, 2 cookies per pack', price: 1288)
snack29 = Snack.create!(name: 'Oreo Original Chocolate Sandwich Cookies', description: 'Pack of 3, 19.1 oz. packages', price: 1068)
snack30 = Snack.create!(name: 'Pepperidge Farm Milano Dark Chocolate Cookies Multipack Tub', description: '20 packs, 2 cookies per pack', price: 799)
snack31 = Snack.create!(name: 'Royal Dansk Danish Butter Cookies', description: '24 oz. tin', price: 676)
snack32 = Snack.create!(name: "Tate's Bake Shop Lemon Cookies", description: 'Pack of 4, 7 oz. bags', price: 2240)
snack33 = Snack.create!(name: 'Walkers Pure Butter Shortbread Cookie Fingers', description: 'Pack of 6, 5.3 oz. boxes', price: 2364)
snack34 = Snack.create!(name: '365 Assorted Entertainment Crackers', description: '8.8 oz. box', price: 379)
snack35 = Snack.create!(name: 'Cheez-It Baked Cheese Snack Crackers', description: 'Pack of 40, 1 oz. bags', price: 1379)
snack36 = Snack.create!(name: 'Pepperidge Farm Goldfish Crackers Variety Pack', description: 'Big Smiles variety, pack of 30', price: 998)
snack37 = Snack.create!(name: 'Pepperidge Farm Goldfish Cheddar Crackers', description: 'Pack of 2, 30 oz. cartons', price: 907)
snack38 = Snack.create!(name: 'Happy Belly Original Saltine Crackers', description: '16 oz. box', price: 210)
snack39 = Snack.create!(name: "Kellogg's Original Club Crackers", description: '13.7 oz. box', price: 399)
snack40 = Snack.create!(name: 'Ritz Cheese Nips Wheat Thins Crackers Variety Pack', description: '20 snack packs', price: 952)
snack41 = Snack.create!(name: 'Ritz Creamy Cheese & Peanut Butter Variety Pack', description: '32 snack packs', price: 1279)
snack42 = Snack.create!(name: 'Ritz Original Crackers', description: 'Pack of 3, 6 stacks per pack', price: 1063)
snack43 = Snack.create!(name: 'Triscuit Original Whole Grain Wheat Crackers', description: '12.5 oz. box', price: 359)
snack44 = Snack.create!(name: '365 Organic Diced Peaches & Pears Fruit Cups', description: 'Pack of 4, 4 oz. cups', price: 349)
snack45 = Snack.create!(name: "Annie's Organic Berry Patch Bunny Fruit Snacks", description: 'Pack of 5, 0.8 oz. pouches', price: 399)
snack46 = Snack.create!(name: "Annie's Organic Strawberry Swirly & Bendy Berry Fruit Tape", description: '12 rolls', price: 1023)
snack47 = Snack.create!(name: 'Black Forest Juicy Burst Mixed Fruit Snacks', description: 'Pack of 40, 0.8 oz. pouches', price: 678)
snack48 = Snack.create!(name: 'Black Forest Organic Berry Medley Fruit Snacks', description: 'Pack of 24, 0.8 oz. pouches', price: 2499)
snack49 = Snack.create!(name: 'Dole Cherry & Mixed Fruit Cups', description: 'Pack of 12, 4 oz. cups', price: 584)
snack50 = Snack.create!(name: 'Betty Crocker Fruit Roll-Ups Variety Pack', description: 'Pack of 10, 0.5 oz. rolls', price: 229)
snack51 = Snack.create!(name: 'Fruit Gushers Variety Pack', description: '20 pouches', price: 387)
snack52 = Snack.create!(name: "Mott's Assorted Flavor Fruit Snacks", description: 'Pack of 40, 0.8 oz. pouches', price: 1036)
snack53 = Snack.create!(name: 'Stretch Island Assorted Fruit Leathers', description: '48 count', price: 1742)
snack54 = Snack.create!(name: "Welch's Berries & Cherries Fruit Snacks", description: '40 count', price: 979)
snack55 = Snack.create!(name: "Welch's Mixed Fruit Snacks", description: '40 count', price: 979)
snack56 = Snack.create!(name: "Welch's Strawberry Fruit Snacks", description: '10 count', price: 245)
snack57 = Snack.create!(name: "Welch's Fruit Snacks Variety Pack", description: '40 count', price: 979)
snack58 = Snack.create!(name: '365 Unroasted Organic Cashews', description: '10 oz. bag', price: 799)
snack59 = Snack.create!(name: 'Emerald Nuts Variety Pack', description: '18 packs', price: 2149)
snack60 = Snack.create!(name: 'Happy Belly Cranberry & Nuts Trail Mix', description: '40 oz. bag', price: 1399)
snack61 = Snack.create!(name: 'Hunter Mix Honey Roasted Southern Style Nuts', description: '23 oz. container', price: 824)
snack62 = Snack.create!(name: 'Kirkland Signature Unsalted Mixed Nuts', description: '1.13 kg container', price: 2413)
snack63 = Snack.create!(name: 'NOW Dry Roasted Sea Salted Macadamia Nuts', description: '9 oz. package', price: 1258)
snack64 = Snack.create!(name: 'Nut Harvest Nut & Chocolate Mix', description: '37 oz. container', price: 1799)
snack65 = Snack.create!(name: 'Planters Salted Cocktail Peanuts', description: '16 oz. resealable container', price: 399)
snack66 = Snack.create!(name: 'Planters Deluxe Lightly Salted Mixed Nuts', description: '15.25 oz. resealable container', price: 869)
snack67 = Snack.create!(name: 'Planters Deluxe Whole Cashews', description: '2.25 oz. container', price: 319)
snack68 = Snack.create!(name: 'Planters Deluxe Roasted Pecans', description: '8 oz. container', price: 909)
snack69 = Snack.create!(name: 'Wonderful Pistachios Multipack', description: 'Pack of 9, 0.75 oz. bags', price: 994)
snack70 = Snack.create!(name: 'Act II Butter Lovers Microwave Popcorn', description: 'Pack of 12, 2.75 oz. bags', price: 638)
snack71 = Snack.create!(name: 'Pop Secret Homestyle Popcorn', description: 'Pack of 30', price: 1779)
snack72 = Snack.create!(name: 'Happy Belly Pretzel Sticks', description: '16 oz. bag', price: 558)
snack73 = Snack.create!(name: "Jack Link's Original Beef Jerky", description: 'Pack of 20, 0.625 oz. bags', price: 2333)
snack74 = Snack.create!(name: "Kellogg's Original Rice Krispies Marshmallow Treats", description: 'Pack of 54, 0.78 oz. bars', price: 1499)
snack75 = Snack.create!(name: 'Nutella Chocolate Hazelnut Spread & Breadsticks', description: 'Pack of 12, 1.8 oz. containers', price: 1608)
snack76 = Snack.create!(name: 'Quaker Chewy Dipps Granola Bars Variety Pack', description: '58 bars', price: 1299)
snack77 = Snack.create!(name: 'Rold Gold Cheddar Tiny Twists Pretzels', description: '10 oz. bag', price: 299)
