# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

require 'open-uri'

User.destroy_all
Snack.destroy_all
Item.destroy_all

user1 = User.create!(username: 'Demo', email: 'demo@demo.com', password: 'hunter12')
user2 = User.create!(username: 'walkie_talkie', email: 'walker@aa.io', password: 'hunter12')
user3 = User.create!(username: 'chairis', email: 'charis@aa.io', password: 'hunter12')
user4 = User.create!(username: 'AllYouCanEat', email: 'ayce@aa.io', password: 'hunter12')

snack1 = Snack.create!(name: 'Airheads Xtremes Rainbow Berry Sour Candy Belts', description: 'Pack of 12, 3 oz. bags', rating: 0, price: 3999)
snack2 = Snack.create!(name: 'Big Sour Patch Kids Chewy Candy', description: 'Individually wrapped, 240 count box', rating: 0, price: 1358)
snack3 = Snack.create!(name: 'Jolly Rancher Assorted Fruit Flavored Hard Candy', description: '360 individually wrapped pieces, 5 lb. bag', rating: 0, price: 2349)
snack4 = Snack.create!(name: 'Life Savers Hard Candy 5 Flavors', description: '50 oz. party size bag', rating: 0, price: 899)
snack5 = Snack.create!(name: 'Mentos Chewy Mint Fruit Candy', description: 'Pack of 6, 15 piece rolls', rating: 0, price: 1816)
snack6 = Snack.create!(name: 'Nerds Rope Rainbow Candy', description: 'Pack of 24, 0.92 oz. packages', rating: 0, price: 1899)
snack7 = Snack.create!(name: 'Red Vines Original Red Licorice Candy Twists', description: '3.5 lb. container', rating: 0, price: 872)
snack8 = Snack.create!(name: "Reese's Hershey's and Kit Kat Assorted Milk Chocolate Miniatures Candy", description: 'Individually wrapped, 265 piece bag', rating: 0, price: 2595)
snack9 = Snack.create!(name: 'Ring Pop Assorted Flavor Lollipops Party Pack', description: '20 count bag', rating: 0, price: 698)
snack10 = Snack.create!(name: "MnM's Snickers 3 Musketeers Skittles Starburst Variety Mix", description: '30 full size packs', rating: 0, price: 3335)
snack11 = Snack.create!(name: 'Snickers Twix 3 Musketeers Milky Way Chocolate Variety Mix', description: '240 inividually wrapped pieces', rating: 0, price: 3124)
snack12 = Snack.create!(name: 'Tootsie Roll Chocolate Twist Midgees', description: '700 count, resealable bag', rating: 0, price: 1911)
snack13 = Snack.create!(name: "Cheetos Lay's Fritos Ruffles Funyuns Doritos Variety Pack", description: '40 count party mix', rating: 0, price: 1798)
snack14 = Snack.create!(name: 'Doritos Cool Ranch Tortilla Chips', description: '14.5 oz. party size bag', rating: 0, price: 450)
snack15 = Snack.create!(name: 'Kettle Brand Organic Sea Salt Potato Chips', description: '5 oz. bag', rating: 0, price: 329)
snack16 = Snack.create!(name: 'Pringles Potato Crisp Chips Variety Pack Snack Stacks', description: 'Pack of 36, 0.67 oz. cups', rating: 0, price: 1499)
snack17 = Snack.create!(name: 'Ruffles Original Potato Chips', description: '13 oz. party size bag', rating: 0, price: 469)
snack18 = Snack.create!(name: 'Ruffles Cheddar and Sour Cream Potato Chips', description: '12.5 oz. party size bag', rating: 0, price: 459)
snack19 = Snack.create!(name: 'Ruffles Sour Cream and Onion Potato Chips', description: '8 oz. bag', rating: 0, price: 399)
snack20 = Snack.create!(name: 'Sunchips Multigrain Chips Variety Pack', description: '40 count pack', rating: 0, price: 1398)
snack21 = Snack.create!(name: "Sunchips Smartfood Doritos Lay's Cheetos Variety Pack", description: '35 count pack', rating: 0, price: 1499)
snack22 = Snack.create!(name: 'Tostitos Hint of Lime Tortilla Chips', description: '11 oz. bag', rating: 0, price: 349)
snack23 = Snack.create!(name: 'Tostitos Scoops Tortilla Chips', description: '10 oz. bag', rating: 0, price: 399)
snack24 = Snack.create!(name: 'Biscoff Lotus Cookies', description: '20 packs, 2 cookies per pack', rating: 0, price: 1090)
snack25 = Snack.create!(name: 'Chips Ahoy Original and Chewy Chocolate Chip Cookies Bundle', description: '3 family size packages', rating: 0, price: 1266)
snack26 = Snack.create!(name: 'Famous Amos Chocolate Chip Cookies', description: 'Pack of 36, 2 oz. pouches', rating: 0, price: 1918)
snack27 = Snack.create!(name: "Grandma's Cookies Variety Pack", description: 'Pack of 30', rating: 0, price: 1498)
snack28 = Snack.create!(name: 'Oreo Chips Ahoy Nutter Butter Cookie Snacks Variety Pack', description: '56 snack packs, 2 cookies per pack', rating: 0, price: 1288)
snack29 = Snack.create!(name: 'Oreo Original Chocolate Sandwich Cookies', description: 'Pack of 3, 19.1 oz. packages', rating: 0, price: 1068)
snack30 = Snack.create!(name: 'Pepperidge Farm Milano Dark Chocolate Cookies Multipack Tub', description: '20 packs, 2 cookies per pack', rating: 0, price: 799)
snack31 = Snack.create!(name: 'Royal Dansk Danish Butter Cookies', description: '24 oz. tin', rating: 0, price: 676)
snack32 = Snack.create!(name: "Tate's Bake Shop Lemon Cookies", description: 'Pack of 4, 7 oz. bags', rating: 0, price: 2240)
snack33 = Snack.create!(name: 'Walkers Pure Butter Assorted Shortbread Cookies', description: 'Pack of 6, 8.8 oz. boxes', rating: 5, price: 2999)
snack34 = Snack.create!(name: '365 Assorted Entertainment Crackers', description: '8.8 oz. box', rating: 0, price: 379)
snack35 = Snack.create!(name: 'Cheez-It Baked Cheese Snack Crackers', description: 'Pack of 40, 1 oz. bags', rating: 0, price: 1379)
snack36 = Snack.create!(name: 'Pepperidge Farm Goldfish Crackers Variety Pack', description: 'Big Smiles variety, pack of 30', rating: 0, price: 998)
snack37 = Snack.create!(name: 'Pepperidge Farm Goldfish Cheddar Crackers', description: 'Pack of 2, 30 oz. cartons', rating: 3.5, price: 907)
snack38 = Snack.create!(name: 'Happy Belly Original Saltine Crackers', description: '16 oz. box', rating: 0, price: 210)
snack39 = Snack.create!(name: "Kellogg's Original Club Crackers", description: '13.7 oz. box', rating: 0, price: 399)
snack40 = Snack.create!(name: 'Ritz Cheese Nips Wheat Thins Crackers Variety Pack', description: '20 snack packs', rating: 0, price: 952)
snack41 = Snack.create!(name: 'Ritz Creamy Cheese and Peanut Butter Variety Pack', description: '32 snack packs', rating: 0, price: 1279)
snack42 = Snack.create!(name: 'Ritz Original Crackers', description: 'Pack of 3, 6 stacks per pack', rating: 0, price: 1063)
snack43 = Snack.create!(name: 'Triscuit Original Whole Grain Wheat Crackers', description: '12.5 oz. box', rating: 0, price: 359)
snack44 = Snack.create!(name: '365 Organic Diced Peaches and Pears Fruit Cups', description: 'Pack of 4, 4 oz. cups', rating: 0, price: 349)
snack45 = Snack.create!(name: "Annie's Organic Berry Patch Bunny Fruit Snacks", description: 'Pack of 5, 0.8 oz. pouches', rating: 0, price: 399)
snack46 = Snack.create!(name: "Annie's Organic Strawberry Swirly and Bendy Berry Fruit Tape", description: '12 rolls', rating: 0, price: 1023)
snack47 = Snack.create!(name: 'Black Forest Juicy Burst Mixed Fruit Snacks', description: 'Pack of 40, 0.8 oz. pouches', rating: 0, price: 678)
snack48 = Snack.create!(name: 'Black Forest Organic Berry Medley Fruit Snacks', description: 'Pack of 24, 0.8 oz. pouches', rating: 0, price: 2499)
snack49 = Snack.create!(name: 'Dole Cherry and Mixed Fruit Cups', description: 'Pack of 12, 4 oz. cups', rating: 0, price: 584)
snack50 = Snack.create!(name: 'Betty Crocker Fruit Roll-Ups Variety Pack', description: 'Pack of 10, 0.5 oz. rolls', rating: 0, price: 229)
snack51 = Snack.create!(name: 'Fruit Gushers Variety Pack', description: '20 pouches', rating: 0, price: 387)
snack52 = Snack.create!(name: "Mott's Assorted Flavor Fruit Snacks", description: 'Pack of 40, 0.8 oz. pouches', rating: 0, price: 1036)
snack53 = Snack.create!(name: 'Stretch Island Assorted Fruit Leathers', description: '48 count', rating: 0, price: 1742)
snack54 = Snack.create!(name: "Welch's Berries and Cherries Fruit Snacks", description: '40 count', rating: 0, price: 979)
snack55 = Snack.create!(name: "Welch's Mixed Fruit Snacks", description: '40 count', rating: 0, price: 979)
snack56 = Snack.create!(name: "Welch's Strawberry Fruit Snacks", description: '10 count', rating: 0, price: 245)
snack57 = Snack.create!(name: "Welch's Fruit Snacks Variety Pack", description: '40 count', rating: 0, price: 979)
snack58 = Snack.create!(name: '365 Unroasted Organic Cashews', description: '10 oz. bag', rating: 0, price: 799)
snack59 = Snack.create!(name: 'Emerald Nuts Variety Pack', description: '18 packs', rating: 0, price: 2149)
snack60 = Snack.create!(name: 'Happy Belly Cranberry and Nuts Trail Mix', description: '40 oz. bag', rating: 0, price: 1399)
snack61 = Snack.create!(name: 'Hunter Mix Honey Roasted Southern Style Nuts', description: '23 oz. container', rating: 0, price: 824)
snack62 = Snack.create!(name: 'Kirkland Signature Unsalted Mixed Nuts', description: '1.13 kg container', rating: 0, price: 2413)
snack63 = Snack.create!(name: 'NOW Dry Roasted Sea Salted Macadamia Nuts', description: '9 oz. package', rating: 0, price: 1258)
snack64 = Snack.create!(name: 'Nut Harvest Nut and Chocolate Mix', description: '37 oz. container', rating: 0, price: 1799)
snack65 = Snack.create!(name: 'Planters Salted Cocktail Peanuts', description: '16 oz. resealable container', rating: 0, price: 399)
snack66 = Snack.create!(name: 'Planters Deluxe Lightly Salted Mixed Nuts', description: '15.25 oz. resealable container', rating: 0, price: 869)
snack67 = Snack.create!(name: 'Planters Deluxe Whole Cashews', description: '2.25 oz. container', rating: 0, price: 319)
snack68 = Snack.create!(name: 'Planters Deluxe Roasted Pecans', description: '8 oz. container', rating: 0, price: 909)
snack69 = Snack.create!(name: 'Wonderful Pistachios Multipack', description: 'Pack of 9, 0.75 oz. bags', rating: 0, price: 994)
snack70 = Snack.create!(name: 'Act II Butter Lovers Microwave Popcorn', description: 'Pack of 12, 2.75 oz. bags', rating: 0, price: 638)
snack71 = Snack.create!(name: 'Pop Secret Homestyle Popcorn', description: 'Pack of 30', rating: 0, price: 1779)
snack72 = Snack.create!(name: 'Happy Belly Pretzel Sticks', description: '16 oz. bag', rating: 0, price: 558)
snack73 = Snack.create!(name: "Jack Link's Original Beef Jerky", description: 'Pack of 20, 0.625 oz. bags', rating: 0, price: 2333)
snack74 = Snack.create!(name: "Kellogg's Original Rice Krispies Marshmallow Treats", description: 'Pack of 54, 0.78 oz. bars', rating: 0, price: 1499)
snack75 = Snack.create!(name: 'Nutella Chocolate Hazelnut Spread and Breadsticks', description: 'Pack of 12, 1.8 oz. containers', rating: 0, price: 1608)
snack76 = Snack.create!(name: 'Quaker Chewy Dipps Granola Bars Variety Pack', description: '58 bars', rating: 0, price: 1299)
snack77 = Snack.create!(name: 'Rold Gold Cheddar Tiny Twists Pretzels', description: '10 oz. bag', rating: 0, price: 299)

snack1.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Candy/airheads-xtremes.jpg'), filename: 'airheads-xtremes.jpg')
snack2.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Candy/big-sour-patch-kids.jpg'), filename: 'big-sour-patch-kids.jpg')
snack3.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Candy/jolly-rancher-hard-candy.jpg'), filename: 'jolly-rancher-hard-candy.jpg')
snack4.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Candy/life-savers-hard-candy.jpg'), filename: 'life-savers-hard-candy.jpg')
snack5.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Candy/mentos-fruit-mints.jpg'), filename: 'mentos-fruit-mints.jpg')
snack6.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Candy/nerds-rope-rainbow.jpg'), filename: 'nerds-rope-rainbow.jpg')
snack7.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Candy/red-vines-licorice.jpg'), filename: 'red-vines-licorice.jpg')
snack8.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Candy/reese-miniature-cups-hershey-milk-chocolate-kit-kat-variety-pack.jpg'), filename: 'reese-miniature-cups-hershey-milk-chocolate-kit-kat-variety-pack.jpg')
snack9.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Candy/ring-pop-party-pack.jpg'), filename: 'ring-pop-party-pack.jpg')
snack10.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Candy/skittles-starburst-3-musketeers-mnm-snickers-variety-pack.jpg'), filename: 'skittles-starburst-3-musketeers-mnm-snickers-variety-pack.jpg')
snack11.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Candy/snickers-3-musketeers-milky-way-twix-chocolate-variety-pack.jpg'), filename: 'snickers-3-musketeers-milky-way-twix-chocolate-variety-pack.jpg')
snack12.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Candy/tootsie-roll-midgees.jpg'), filename: 'tootsie-roll-midgees.jpg')
snack13.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Chips/cheetos-lays-fritos-ruffles-funyuns-doritos-variety-pack.jpg'), filename: 'cheetos-lays-fritos-ruffles-funyuns-doritos-variety-pack.jpg')
snack14.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Chips/doritos-cool-ranch.jpg'), filename: 'doritos-cool-ranch.jpg')
snack15.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Chips/kettle-organic-sea-salt.jpg'), filename: 'kettle-organic-sea-salt.jpg')
snack16.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Chips/pringles-assorted.jpg'), filename: 'pringles-assorted.jpg')
snack17.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Chips/ruffles-original.jpg'), filename: 'ruffles-original.jpg')
snack18.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Chips/ruffles-cheddar-sour-cream.jpg'), filename: 'ruffles-cheddar-sour-cream.jpg')
snack19.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Chips/ruffles-sour-cream-onion.jpg'), filename: 'ruffles-sour-cream-onion.jpg')
snack20.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Chips/sun-chips-assorted.jpg'), filename: 'sun-chips-assorted.jpg')
snack21.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Chips/sun-chips-smartfood-doritos-lays-cheetos-variety-pack.jpg'), filename: 'sun-chips-smartfood-doritos-lays-cheetos-variety-pack.jpg')
snack22.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Chips/tostitos-hint-lime.jpg'), filename: 'tostitos-hint-lime.jpg')
snack23.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Chips/tostitos-scoops.jpg'), filename: 'tostitos-scoops.jpg')
snack24.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Cookies/biscoff.jpg'), filename: 'biscoff.jpg')
snack25.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Cookies/chips-ahoy-assorted.jpg'), filename: 'chips-ahoy-assorted.jpg')
snack26.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Cookies/famous-amos-chocolate-chip.jpg'), filename: 'famous-amos-chocolate-chip.jpg')
snack27.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Cookies/grandma-assorted.jpg'), filename: 'grandma-assorted.jpg')
snack28.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Cookies/oreo-chips-ahoy-nutter-butter-variety-pack.jpg'), filename: 'oreo-chips-ahoy-nutter-butter-variety-pack.jpg')
snack29.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Cookies/original-oreos.jpg'), filename: 'original-oreos.jpg')
snack30.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Cookies/pepperidge-farm-milano-dark-chocolate.jpg'), filename: 'pepperidge-farm-milano-dark-chocolate.jpg')
snack31.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Cookies/royal-dansk-danish-butter-cookies.jpg'), filename: 'royal-dansk-danish-butter-cookies.jpg')
snack32.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Cookies/tate-bake-shop-lemon-cookies.jpg'), filename: 'tate-bake-shop-lemon-cookies.jpg')
snack33.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Cookies/walker-assorted-shortbread.jpg'), filename: 'walker-assorted-shortbread.jpg')
snack34.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Crackers/365-assorted-entertainment.jpg'), filename: '365-assorted-entertainment.jpg')
snack35.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Crackers/cheez-its.jpg'), filename: 'cheez-its.jpg')
snack36.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Crackers/goldfish-big-smiles-assorted.jpg'), filename: 'goldfish-big-smiles-assorted.jpg')
snack37.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Crackers/goldfish-cheddar.jpg'), filename: 'goldfish-cheddar.jpg')
snack38.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Crackers/happy-belly-original-saltine-crackers.jpg'), filename: 'happy-belly-original-saltine-crackers.jpg')
snack39.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Crackers/kellogg-club-crackers.jpg'), filename: 'kellogg-club-crackers.jpg')
snack40.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Crackers/ritz-cheese-nips-wheat-thins.jpg'), filename: 'ritz-cheese-nips-wheat-thins.jpg')
snack41.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Crackers/ritz-cheese-peanut-butter-assorted.jpg'), filename: 'ritz-cheese-peanut-butter-assorted.jpg')
snack42.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Crackers/ritz-original-crackers.jpg'), filename: 'ritz-original-crackers.jpg')
snack43.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Crackers/triscuit-original-sea-salt.jpg'), filename: 'triscuit-original-sea-salt.jpg')
snack44.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Fruit-Snacks/365-diced-peach-pear-cups.jpg'), filename: '365-diced-peach-pear-cups.jpg')
snack45.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Fruit-Snacks/annie-organic-berry-patch-fruit-snacks.jpg'), filename: 'annie-organic-berry-patch-fruit-snacks.jpg')
snack46.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Fruit-Snacks/annie-organic-fruit-tape-variety-pack.jpg'), filename: 'annie-organic-fruit-tape-variety-pack.jpg')
snack47.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Fruit-Snacks/black-forest-juicy-burst-mixed-fruit-snacks.jpg'), filename: 'black-forest-juicy-burst-mixed-fruit-snacks.jpg')
snack48.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Fruit-Snacks/black-forest-organic-berry-medley-fruit-snacks.jpg'), filename: 'black-forest-organic-berry-medley-fruit-snacks.jpg')
snack49.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Fruit-Snacks/dole-cherry-mixed-fruit-cups.jpg'), filename: 'dole-cherry-mixed-fruit-cups.jpg')
snack50.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Fruit-Snacks/fruit-roll-ups-variety-pack.jpg'), filename: 'fruit-roll-ups-variety-pack.jpg')
snack51.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Fruit-Snacks/mega-fruit-gushers-variety-pack.jpg'), filename: 'mega-fruit-gushers-variety-pack.jpg')
snack52.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Fruit-Snacks/mott-assorted-fruit-snacks.jpg'), filename: 'mott-assorted-fruit-snacks.jpg')
snack53.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Fruit-Snacks/stretch-island-assorted-fruit-leather.jpg'), filename: 'stretch-island-assorted-fruit-leather.jpg')
snack54.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Fruit-Snacks/welch-berries-cherries-fruit-snacks.jpg'), filename: 'welch-berries-cherries-fruit-snacks.jpg')
snack55.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Fruit-Snacks/welch-mixed-fruit-snacks.jpg'), filename: 'welch-mixed-fruit-snacks.jpg')
snack56.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Fruit-Snacks/welch-strawberry-fruit-snacks.jpg'), filename: 'welch-strawberry-fruit-snacks.jpg')
snack57.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Fruit-Snacks/welch-variety-fruit-snacks.jpg'), filename: 'welch-variety-fruit-snacks.jpg')
snack58.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Nuts/365-unroasted-organic-cashews.jpg'), filename: '365-unroasted-organic-cashews.jpg')
snack59.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Nuts/emerald-variety-pack.jpg'), filename: 'emerald-variety-pack.jpg')
snack60.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Nuts/happy-belly-cranberry-nuts-trail-mix.jpg'), filename: 'happy-belly-cranberry-nuts-trail-mix.jpg')
snack61.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Nuts/hunter-mix-honey-roasted-nuts.jpg'), filename: 'hunter-mix-honey-roasted-nuts.jpg')
snack62.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Nuts/kirkland-signature-unsalted-mixed-nuts.jpg'), filename: 'kirkland-signature-unsalted-mixed-nuts.jpg')
snack63.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Nuts/now-dry-roasted-sea-salted-macadamia-nuts.jpg'), filename: 'now-dry-roasted-sea-salted-macadamia-nuts.jpg')
snack64.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Nuts/nut-harvest-trail-mix.jpg'), filename: 'nut-harvest-trail-mix.jpg')
snack65.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Nuts/planters-cocktail-peanuts.jpg'), filename: 'planters-cocktail-peanuts.jpg')
snack66.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Nuts/planters-deluxe-lightly-salted-mixed-nuts.jpg'), filename: 'planters-deluxe-lightly-salted-mixed-nuts.jpg')
snack67.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Nuts/planters-deluxe-whole-cashews.jpg'), filename: 'planters-deluxe-whole-cashews.jpg')
snack68.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Nuts/planters-roasted-pecans.jpg'), filename: 'planters-roasted-pecans.jpg')
snack69.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Nuts/wonderful-pistachios.jpg'), filename: 'wonderful-pistachios.jpg')
snack70.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Other/act-ii-butter-lovers-popcorn.jpg'), filename: 'act-ii-butter-lovers-popcorn.jpg')
snack71.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Other/pop-secret-homestyle-popcorn.jpg'), filename: 'pop-secret-homestyle-popcorn.jpg')
snack72.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Other/happy-belly-pretzel-sticks.jpg'), filename: 'happy-belly-pretzel-sticks.jpg')
snack73.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Other/jack-link-original-beef-jerky.jpg'), filename: 'jack-link-original-beef-jerky.jpg')
snack74.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Other/kellogg-original-rice-krispie-treats.jpg'), filename: 'kellogg-original-rice-krispie-treats.jpg')
snack75.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Other/nutella-breadsticks.jpg'), filename: 'nutella-breadsticks.jpg')
snack76.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Other/quaker-chewy-dipps-granola-bars.jpg'), filename: 'quaker-chewy-dipps-granola-bars.jpg')
snack77.photo.attach(io: URI.open('https://amanom-dev.s3.us-west-1.amazonaws.com/New-Amazon-Snack-Images/Other/rold-gold-tiny-twists-cheddar-pretzels.jpg'), filename: 'rold-gold-tiny-twists-cheddar-pretzels.jpg')

item1 = Item.create!(snack_id: snack2.id, user_id: user1.id, order_id: nil, quantity: 3)
item2 = Item.create!(snack_id: snack37.id, user_id: user1.id, order_id: nil, quantity: 4)
item3 = Item.create!(snack_id: snack56.id, user_id: user1.id, order_id: nil, quantity: 3)

review1 = Review.create!(user_id: user2.id, snack_id: snack33.id, title: 'yummy', body: '10/10 would ditch my cohort for these', stars: 5)
review2 = Review.create!(user_id: user3.id, snack_id: snack37.id, title: 'yummy', body: '10/10 would ditch my cohort for these', stars: 5)
review3 = Review.create!(user_id: user4.id, snack_id: snack37.id, title: 'eh', body: "they're all right", stars: 2)
